/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Untitled.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Untitled.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Mesh_0.geometry} material={materials.Material_0} />
      <mesh geometry={nodes.Mesh_0001.geometry} material={materials.Material_0} position={[0.387, 0.192, -0.049]} rotation={[0.021, 0.009, 0.045]} />
    </group>
  )
}

useGLTF.preload('/Untitled.glb')
